interface:
  default: HTMLMailMailSystem
  htmlmail: HTMLMailMailSystem
_core:
  default_config_hash: rYgt7uhPafP2ngaN_ZUPFuyI4KdE0zU868zLNSlzKoE
defaults:
  formatter: htmlmail
  sender: SMTPMailSystem
theme: current
modules:
  htmlmail:
    none:
      formatter: htmlmail
      sender: SMTPMailSystem
