credentials_config.credentials.*:
  type: config_entity
  label: credentials
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    url:
      type: string
      label: 'Endpoint URL'
    api_key:
      type: string
      label: 'API Key'
    api_secret:
      type: string
      label: 'API Secret'
