entity.credentials.collection:
  path: '/admin/config/services/credentials'
  defaults:
    _entity_list: 'credentials'
    _title: 'Credentials configuration'
  requirements:
    _permission: 'administer site configuration'

entity.credentials.add_form:
  path: '/admin/config/services/credentials/add'
  defaults:
    _entity_form: 'credentials.add'
    _title: 'Add credentials'
  requirements:
    _permission: 'administer site configuration'

entity.credentials.edit_form:
  path: '/admin/config/services/credentials/{credentials}'
  defaults:
    _entity_form: 'credentials.edit'
    _title: 'Edit credentials'
  requirements:
    _permission: 'administer site configuration'

entity.credentials.delete_form:
  path: '/admin/config/services/credentials/{credentials}/delete'
  defaults:
    _entity_form: 'credentials.delete'
    _title: 'Delete credentials'
  requirements:
    _permission: 'administer site configuration'

entity.credentials.preview_page:
  path: '/admin/config/services/credentials/{credentials}/preview'
  defaults:
    _controller: '\Drupal\credentials_config\Controller\CredentialsController::preview'
    _title: 'Preview credentials configuration'
  requirements:
    _permission: 'administer site configuration'
